### ISSUE TITLE
Help, How conect redis and mysql from pc to docker?

### ISSUE THREAD

**Issue by accnex569** [dmp1ce/CoiniumServ-Dockerfile#1]
Help, How conect redis and mysql from pc to docker?

**Comment by dmp1ce** [comment]
I would suggest running reddis or mysql in another docker container and organizing the containers using Docker Compose.

If you don't want to do that then perhaps there are some workaround to get your container to connect back to your host. I found this article which is a little old, but might help. https://nickjanetakis.com/blog/docker-tip-35-connect-to-a-database-running-on-your-docker-host

This is beyond the scope of this project, so I'm closing.
