### ISSUE TITLE
How do you create a mysql database with username and password?

### ISSUE THREAD

**Issue by spaced-out-mvc** [dmp1ce/CoiniumServ-Dockerfile#2]
How do you create a mysql database with username and password?

As this seems to be an 100% requirement?

**Comment by dmp1ce** [comment]
I agree, unfortunately the database is beyond the scope of this Dockerfile. If someone makes a Docker Compose repo which ties together Coinium containers with a MySQL container, I'll happily link to it.

Closing because I'm not planning on implementing a database here.
